[package]
name = "app"
version = "0.31.0"
edition = "2021"

[lib]
name = "sendme_app"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
sendme-lib = { path = "../../lib" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.34.0", features = ["full"] }
tauri = { version = "2", features = ["tracing"] }
tauri-plugin-shell = "2"
tracing = "0.1"
tracing-subscriber = "0.3"
uuid = { version = "1", features = ["v4"] }

[build-dependencies]
tauri-build = { version = "2", features = [] }
